### ISSUE TITLE
Dependabot PRs have restricted permissions for testing

### ISSUE THREAD

**Issue by nwiltsie** [uclahs-cds/tool-Nextflow-action#31]
Per [this link](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions):

> By default, GitHub Actions workflows triggered by Dependabot get a GITHUB_TOKEN with read-only permissions. You can use the permissions key in your workflow to increase the access for the token

Additionally, dependabot has a [separate set of available secrets](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#about-encrypted-secrets-for-dependabot):

> Dependabot secrets also include secrets that are used by GitHub Actions workflows triggered by Dependabot pull requests. Dependabot itself may not use these secrets, but the workflows require them.

That means that this construct to use `secrets.UCLAHS_CDS_REPO_READ_TOKEN`...

https://github.com/uclahs-cds/tool-Nextflow-action/blob/da23bc9d87fda1d5b6751d3b671057d0b4d7e297/.github/workflows/nextflow-tests.yml#L245-L255

... _does not_ work on dependabot PRs.

**Comment by nwiltsie** [comment]
Per https://securitylab.github.com/research/github-actions-preventing-pwn-requests/, the "official" solution to this is to have a two-workflow approach - one low-permissions workflow that is triggered by dependabot, and then one high-permissions workflow triggered on the [successful conclusion of the first](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) with `workflow_run`.

**Comment by nwiltsie** [comment]
Okay, here is my latest scheme. Each repo now has two workflows:

* A combined workflow that triggers on:
    * `push`s to `main` (can only happen if the user has privileges)
    * `issue_comment`s that start with `/fix-tests` or `/run-tests`
    * `pull_request_target`s to `main`
* Another that triggers on `workflow_run`, requiring success of the (named) prior workflow and calls the reusable

The first workflow will fail for `issue_comment`s and `pull_request_target`s that do not come from repository collaborators and will post a comment about that. A new trigger is if a collaborator comments `/run-tests`, which enables a trusted collaborator to run the tests on behalf of a sneaky outsider.

```mermaid
flowchart

    subgraph workflow [Reusable Workflow]
        direction TB
        reused[[Discovery]]
        reuset1[[Test #1]]
        reuset2[[Test #2]]
        reuset3[[Test #3]]
        reuses[[Summary]]

        reused --> reuset1 --> reuses
        reused --> reuset2 --> reuses
        reused --> reuset3 --> reuses
    end

    subgraph workflow3 [Repo Workflow 2]
        direction TB
        workflow_run[/"workflow_run event\n(workflow #1 was successful)"/]
    end

    subgraph workflow1 [Repo Workflow 1]
        direction TB
        pull_request[/"pull_request_target event\n(to main)"/]
        push[/"push event (to main)"/]
        issue_comment[/"issue_comment event (on PR,\ntext starts with '/fix-tests' or '/run-tests')"/]
        

        wf1_user_check{{User is\ncollaborator?}}

        issue_comment --> wf1_user_check
        pull_request --> wf1_user_check

        trust[Post comment\nabout collaborators\nand /run-tests]:::medium

        wf1_user_check -->|No| trust --> wf1fail([Fail])
        wf1_user_check -->|Yes|wf1success([Succeed])

        push --> wf1success

    end

    workflow_run --> workflow

    classDef medium fill:#fb0;
```

**Comment by nwiltsie** [comment]
The second workflow will escape the dependabot restrictions with that `workflow_run` trigger. The first workflow will only succeed if the triggering user is a collaborator, making me more comfortable about adding permissions to the second workflow.

**Comment by dan-knight** [comment]
Thanks for looking into this. This all makes sense to me, and should be fairly safe. My only concern is that some of these measures rely on the GitHub Action workflow YAML file being correct (for example, `workflow_dispatch` being used correctly). Automation should surely help with this, but these YAML files always feel difficult to validate imo. Any thoughts on this? Do we just automate as much as possible, document well, and stay vigilant?

**Comment by nwiltsie** [comment]
My current strategy for managing the complexity is reusable workflows - we sink as much complexity as possible into workflows in _this_ repository, then have simple cookie-cutter workflows in other repositories.
